[settings]
experimental = true

[settings.status]
missing_tools = "always"

[tools]
starship = "latest"
node = "latest"
go = "latest"
gotestsum = "latest"
eza = "latest"
fzf = "0.53"
bat = "latest"
lazygit = "latest"
lazydocker = "latest"
ripgrep = "latest"
fd = "latest"
jq = "latest"
pnpm = "latest"
terraform = "latest"
neovim = "0.10.4"
btop = "latest"
